#!/usr/bin/env python3
"""
Batch noise study: run noise_study.py on each assembly file and produce a
unified summary table with PASS/FAIL verdicts.

This is Team 1's primary deliverable script — it answers the question:
"Can we achieve < 5% CV across 20 binaries?"

The script runs noise_study.py (which in turn runs naive-bench or
hyperfine-bench) for each assembly file, collects the per-label CV,
and prints a summary table showing which binaries pass the threshold.

Usage (from repo root):

  # Run on a directory of assembly files (generated by gen_test_assemblies.py):
  python3 scripts/run_noise_batch.py --asm-dir generated_assemblies/ \\
    --repeats 20 --threshold 0.05 \\
    -- --reference examples/abc_ref.cpp \\
       --tests examples/abc_tests.json \\
       --language cpp --use-docker --docker-image gcc:13 \\
       --docker-platform linux/arm64 --extra-ldflags=-lstdc++ --runs 30

  # Or pass individual files:
  python3 scripts/run_noise_batch.py examples/abc_user_arm64.s examples/example2_deepseek.s \\
    --repeats 10 -- --use-docker --docker-image gcc:13 ...

Exit code:
  0  — all binaries pass the CV threshold
  1  — at least one binary fails (or an error occurred)
  2  — usage error (no assembly files provided)
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Locate noise_study.py relative to this script.
# Both scripts live in infra/scripts/.
# ---------------------------------------------------------------------------
NOISE_STUDY_PY = Path(__file__).resolve().parent / "noise_study.py"


def _collect_assemblies(
    positional: list[Path], asm_dir: Path | None
) -> list[Path]:
    """Gather assembly files from positional args or --asm-dir.

    Returns a sorted list of .s files.  Raises SystemExit if none found.
    """
    if positional:
        return sorted(positional)
    if asm_dir is not None:
        files = sorted(asm_dir.glob("*.s"))
        if not files:
            print(
                f"error: no .s files found in {asm_dir}", file=sys.stderr
            )
            raise SystemExit(2)
        return files
    print(
        "error: provide assembly files or --asm-dir", file=sys.stderr
    )
    raise SystemExit(2)


def _run_one(
    asm: Path,
    *,
    repeats: int,
    threshold: float,
    use_hyperfine: bool,
    bench_args: list[str],
) -> dict[str, Any]:
    """Run noise_study.py on a single assembly file.

    Returns the parsed JSON output from noise_study.py, augmented with
    the assembly file path.  On error, returns a dict with an "error" key.
    """
    cmd = [
        sys.executable,
        str(NOISE_STUDY_PY),
        "--repeats",
        str(repeats),
        "--threshold",
        str(threshold),
        "--label",
        asm.stem,
        *(["--use-hyperfine"] if use_hyperfine else []),
        "--",
        str(asm),
        *bench_args,
    ]
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            # Generous timeout: repeats * 20 minutes per repeat + buffer.
            timeout=repeats * 1200 + 300,
        )
    except subprocess.TimeoutExpired:
        return {"error": "timeout", "asm": str(asm)}

    # noise_study.py prints JSON to stdout and a table to stderr.
    # Forward stderr so the user sees per-binary progress.
    if proc.stderr:
        sys.stderr.write(proc.stderr)

    if proc.returncode != 0 and not proc.stdout.strip():
        return {
            "error": f"exit {proc.returncode}: {(proc.stderr or '')[:300]}",
            "asm": str(asm),
        }

    try:
        result = json.loads(proc.stdout)
    except json.JSONDecodeError:
        return {
            "error": f"invalid JSON from noise_study.py",
            "asm": str(asm),
        }
    result["asm"] = str(asm)
    return result


def _extract_cv(result: dict[str, Any], label: str) -> float | None:
    """Pull CV for a label from a noise_study result."""
    summary = result.get("summary", {})
    entry = summary.get(label, {})
    return entry.get("cv")


def main() -> int:
    ap = argparse.ArgumentParser(
        description=(
            "Run noise_study.py on each assembly file and produce a "
            "unified summary table.  Exit 0 only if all binaries pass."
        ),
    )
    ap.add_argument(
        "assemblies",
        nargs="*",
        type=Path,
        help="Assembly files to benchmark.  If omitted, use --asm-dir.",
    )
    ap.add_argument(
        "--asm-dir",
        type=Path,
        default=None,
        help="Directory of .s files to benchmark.",
    )
    ap.add_argument(
        "--repeats",
        type=int,
        default=20,
        help="Repeats per binary for noise_study.py (default: 20).",
    )
    ap.add_argument(
        "--threshold",
        type=float,
        default=0.05,
        help="CV threshold for PASS/FAIL (default: 0.05 = 5%%).",
    )
    ap.add_argument(
        "--use-hyperfine",
        action="store_true",
        help="Use hyperfine-bench instead of naive-bench.",
    )
    ap.add_argument(
        "--json-out",
        type=Path,
        default=None,
        help="Write full per-binary JSON results here.",
    )
    # Everything after -- is forwarded to the benchmark tool via noise_study.
    ap.add_argument(
        "bench_args",
        nargs=argparse.REMAINDER,
        help="Arguments after -- forwarded to the benchmark tool.",
    )
    args = ap.parse_args()

    # Strip the leading "--" separator.
    fwd = args.bench_args
    if fwd and fwd[0] == "--":
        fwd = fwd[1:]

    assemblies = _collect_assemblies(args.assemblies, args.asm_dir)

    print(f"\n{'='*78}", file=sys.stderr)
    print(f"  BATCH NOISE STUDY", file=sys.stderr)
    print(f"  {len(assemblies)} binaries  |  {args.repeats} repeats each  |  threshold: {args.threshold:.2%}", file=sys.stderr)
    print(f"{'='*78}\n", file=sys.stderr)

    # -----------------------------------------------------------------------
    # Run noise study for each assembly file, collecting results.
    # -----------------------------------------------------------------------
    all_results: list[dict[str, Any]] = []
    labels_seen: set[str] = set()

    for idx, asm in enumerate(assemblies, 1):
        print(
            f"\n--- [{idx}/{len(assemblies)}] {asm.name} ---\n",
            file=sys.stderr,
        )
        result = _run_one(
            asm,
            repeats=args.repeats,
            threshold=args.threshold,
            use_hyperfine=args.use_hyperfine,
            bench_args=fwd,
        )
        all_results.append(result)
        if "summary" in result:
            labels_seen.update(result["summary"].keys())

    # -----------------------------------------------------------------------
    # Build and print the summary table.
    # Each row is one assembly file.  Columns show CV for each label.
    # A binary passes if ALL its CVs are below the threshold.
    # -----------------------------------------------------------------------
    # Consistent column ordering: assembly first, then O0..O3.
    label_order = []
    for lbl in ["assembly", "O0", "O1", "O2", "O3"]:
        if lbl in labels_seen:
            label_order.append(lbl)

    # Print header.
    print(f"\n{'='*78}", file=sys.stderr)
    print(f"  BATCH SUMMARY", file=sys.stderr)
    print(f"{'='*78}\n", file=sys.stderr)

    col_w = 10  # width for each CV column
    header = f"  {'Binary':<25}"
    for lbl in label_order:
        header += f" {lbl + ' CV':>{col_w}}"
    header += "   PASS?"
    print(header, file=sys.stderr)
    print("  " + "-" * (25 + (col_w + 1) * len(label_order) + 8), file=sys.stderr)

    pass_count = 0
    fail_count = 0

    for result in all_results:
        asm_path = Path(result.get("asm", "unknown"))
        name = asm_path.stem[:25]

        if "error" in result:
            # This binary errored out — mark as FAIL.
            row = f"  {name:<25}"
            for _ in label_order:
                row += f" {'ERROR':>{col_w}}"
            row += "   FAIL"
            print(row, file=sys.stderr)
            fail_count += 1
            continue

        binary_pass = True
        row = f"  {name:<25}"
        for lbl in label_order:
            cv = _extract_cv(result, lbl)
            if cv is None:
                row += f" {'N/A':>{col_w}}"
            else:
                row += f" {cv:{col_w}.4f}"
                if cv >= args.threshold:
                    binary_pass = False
        row += f"   {'PASS' if binary_pass else 'FAIL'}"
        print(row, file=sys.stderr)

        if binary_pass:
            pass_count += 1
        else:
            fail_count += 1

    total = pass_count + fail_count
    print(file=sys.stderr)
    print(
        f"  Passed: {pass_count}/{total}  |  Failed: {fail_count}/{total}",
        file=sys.stderr,
    )
    if fail_count == 0:
        print(f"  Overall: PASS  (all binaries below {args.threshold:.2%} CV)", file=sys.stderr)
    else:
        print(f"  Overall: FAIL  ({fail_count} binaries above {args.threshold:.2%} CV)", file=sys.stderr)
    print(file=sys.stderr)

    # -----------------------------------------------------------------------
    # Write full JSON results if --json-out was given.
    # -----------------------------------------------------------------------
    if args.json_out:
        full_output = {
            "threshold": args.threshold,
            "repeats": args.repeats,
            "tool": "hyperfine-bench" if args.use_hyperfine else "naive-bench",
            "binaries": all_results,
            "pass_count": pass_count,
            "fail_count": fail_count,
        }
        args.json_out.write_text(
            json.dumps(full_output, indent=2), encoding="utf-8"
        )
        print(f"  Full results written to: {args.json_out}", file=sys.stderr)

    # Exit 0 only if every binary passed.
    return 0 if fail_count == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
